### PR TITLE
Port next to py3.x

### PR DESCRIPTION
**Pull request by nanjekyejoannah**
This PR introduces `x.next()` which is equivalent to `x.__next__()`.

### CODE REVIEW

**Comment by ltratt** [comment]
Dumb question possibly: do we have a test which checks that a warning is raised when `next` is used?

**Comment by nanjekyejoannah** [comment]
Actually no because we also dont have a warning, I keep forgetting if we are supposed to issue a warning for ported stuff, in the last PR, we removed the warning, but I can implement a warning for this if you think its ideal.

**Comment by ltratt** [comment]
IMHO the aim of pygrate3 is to help users migrate their code so that, eventually, they can run on normal python3. If they aren't warned when they use a feature that's in python3, they won't know to fix it.

**Comment by nanjekyejoannah** [comment]
@ltratt standby for me to implement the warnings then from https://github.com/softdevteam/pygrate2/pull/22 as discussed today.

**Comment by nanjekyejoannah** [comment]
@ltratt I have implemented the warning. One redundant method introduced to be able to not overwarn.

**Comment by ltratt** [comment]
Please squash.

**Comment by nanjekyejoannah** [comment]
Squashed.

**Pull request merged**
